### ISSUE TITLE
Refactor Student file group

### ISSUE THREAD

**Issue by shanekenney** [ITC205-Team14/Assignment2#1]
The Student file group includes the following files:

* AppProperties.java
* IStudent.java
* IStudentLister.java
* ListStudentsCTL.java
* Student.java
* StudentManager.java
* StudentMap.java
* StudentProxy.java

Refactor the included files inline with the provided [Java style guide](https://github.com/ITC205-Team14/Assignment2/files/896/Java.Programming.Style.Guidelines.pdf), paying particular attention to the following:

1. Correct formatting
2. Meaningful variable names, in conformance with naming style guidelines - both for variables and for classes.
3. Meaningful method names, in conformance with the style guidelines.

**Note:** If a method or class needs to be renamed that is defined outside your group of files then leave that to the owner of that file. They will be responsible for updating all references to that method, including references outside of their file group.

**Comment by shanekenney** [comment]
Reviewer: @tossoffer
Mediator: @shanekenney

**Comment by brett-a-smith** [comment]
Completed AppProperties.java,, IStudent.java, IStudentLister.java, completed StudentMap.java made ListStudentsCTL.java and Student.java more readable.
