### ISSUE TITLE
Refactor Student Unit Record file group

### ISSUE THREAD

**Issue by shanekenney** [ITC205-Team14/Assignment2#2]
The Student Unit Record file group includes the following files:

* IStudentUnitRecord.java
* StudentUnitRecord.java
* StudentUnitRecordList.java
* StudentUnitRecordManager.java
* StudentUnitRecordMap.java
* StudentUnitRecordProxy.java

Refactor the included files inline with the provided [Java style guide](https://github.com/ITC205-Team14/Assignment2/files/896/Java.Programming.Style.Guidelines.pdf), paying particular attention to the following:

1. Correct formatting
2. Meaningful variable names, in conformance with naming style guidelines - both for variables and for classes.
3. Meaningful method names, in conformance with the style guidelines.

**Note:** If a method or class needs to be renamed that is defined outside your group of files then leave that to the owner of that file. They will be responsible for updating all references to that method, including references outside of their file group.

**Comment by shanekenney** [comment]
Reviewer: @tossoffer 
Mediator: @VinterViking

**Comment by tossoffer** [comment]
Completed reviewing and fixing the code to the specified Java Guidelines in the follows files;

IStudentUnitRecord.java
StudentUnitRecord.java
StudentUnitRecordList.java
StudentUnitRecordManager.java
StudentUnitRecordMap.java
StudentUnitRecordProxy.java

The work was updated to my branch on Friday the 7th of August.
