### ISSUE TITLE
Refactor Main file group

### ISSUE THREAD

**Issue by shanekenney** [ITC205-Team14/Assignment2#4]
The Main file group includes the following files:

* Main.java ✓ 
* XMLManager.java ✓ 
* cgCTL.java ✓ 
* cgUI.java ✓ 

Refactor the included files inline with the provided [Java style guide](https://github.com/ITC205-Team14/Assignment2/files/896/Java.Programming.Style.Guidelines.pdf), paying particular attention to the following:

1. Correct formatting
2. Meaningful variable names, in conformance with naming style guidelines - both for variables and for classes.
3. Meaningful method names, in conformance with the style guidelines.

**Note:** If a method or class needs to be renamed that is defined outside your group of files then leave that to the owner of that file. They will be responsible for updating all references to that method, including references outside of their file group.

**Comment by shanekenney** [comment]
Reviewer: @brett-a-smith 
Mediator: @tossoffer

**Comment by VinterViking** [comment]
All classes and methods that needed to have been changed have been dealt with.

    Main.java ✓
    XMLManager.java ✓
    cgCTL.java ✓
    cgUI.java ✓

**Comment by VinterViking** [comment]
The follow classes had calls to other classes reverted back to make the build work properly.
cgCTL.java 
cgUI.java 
Everything works as of this build.

**Comment by shanekenney** [comment]
Defects have been submitted to CodeReviewer. @VinterViking @tossoffer.
